# The AnVIL -- workspaces, runtimes, buckets, workflows

In this section we learn about

- Cloning a 'WORKSPACES' for coordinating access to particular data
  sets and analyses
- Creating a Notebook runtimes for cloud-based computation
- Understanding the relationship between workspaace, runtime, DATA,
  and NOTEBOOKS.

## Navigation icons

- HAMBURGER
- TEARDROP
- PLUS

## Use an existing workspace

Visit the WORKSPACES page https://anvil.terra.bio/#workspaces

Search for the 'Bioconductor' featured workspace.

- Choose the HAMBURGER menu, 'Your workspaces' item
- Search (at the top of the screen) for 'Bioconductor-BCC2020'
- This should appear under 'My Workspaces'
- Problems?

    - Refresh your browser window & cache, with, e.g., `command-shift-R`
    - Provide your email account to Lori or Nitesh in REMO chat

- Shortcut: https://anvil.terra.bio/#workspaces?filter=Bioconductor-BCC2020

Clone 

- Choose the TEARDROP associated with this workspace
- Select 'Clone'
- Name the workspace, e.g,. `Bioconductor-bcc2020-<YOUR-NAME>` or similar.
- Associate the cloned workspace with the `bioconductor-rpci-bcc2020`
  billing account

## DASHBOARD

Runtimes (top right)

- Select the 'R / Bioconductor...' runtime environment

  - 'What's installed on this environment'
  - Compute power

- Runtime can be used across different workspaces

Google bucket

- Associated with the work space, managed by Terra. Persistent storage.

## DATA

TABLES

- Usually, metadata referencing cloud-based data sets
- Ours: Human Cell Atlas BAM files for a particular study

...

OTHER DATA

- Google bucket content
- Persits even if new runtime selected

## NOTEBOOKS

Existing notebooks -- TEARDROP

- Preview: read-only
- Edit: edit, evaluate, and save changes
- Playground: edit, evalaute, but do not save changes

## WORKFLOWS
